export enum RiskType{
    HIGH_RISK = 'HIGH_RISK',
    HIGH_RISK_FIT_TO_TRAVEL = 'HIGH_RISK_FIT_TO_TRAVEL',
    HIGH_RISK_NOT_FIT_TO_TRAVEL = 'HIGH_RISK_NOT_FIT_TO_TRAVEL',
    LOW_RISK = 'LOW_RISK',
    MEDIUM_RISK = 'MEDIUM_RISK',

}